### ISSUE TITLE
Quest Find the Ancient Hero

### ISSUE THREAD

**Issue by TivTiv** [AbyssWoW/BugTracker#44] opened 2019-02-07 08:42 UTC
Name: Tivam , Beastlover
Faction: Alli 
Location: Icecrown (west)
Quest: https://www.wowhead.com/quest=13133/find-the-ancient-hero

Description: Unable to capture Iskalder - tried it multiple times with or without pet, cc'd and non cc'd. 
He just disapper after the channeling.

**Comment by Udesii** [comment] 2019-02-09 19:28
This issue has been fixed in a temporary way.
You now need to kill Iskalder to complete the quest.


To work as intended I will add a fix to this quest in the future.

**Closed by Udesii** 2019-02-09 19:28 UTC
